spring:
  application:
    name: assembly
  sql:
    init:
      mode: always
      schema-locations: ""
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      schema: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
    enabled: true
server:
  port: 8083
logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN
